name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: aldoborrero/use-nix-action@v2
    
    - name: Hisoka
      run: make hisoka
      
    - name: Killua
      run: make killua
